service: todo-application-backend
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x

functions:
  tasks:
    handler: todos.handler
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http:
          path: todos/{taskId}
          method: put
          cors: true
      - http:
          path: todos
          method: get
          cors: true
      - http:
          path: todos
          method: post
          cors: true
      - http:
          path: todos/{taskId}
          method: delete
          cors: true